apiVersion: v1
kind: Service
metadata:
  name: hellofromhost
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hellofromhost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellofromhost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellofromhost
  template:
    metadata:
      labels:
        app: hellofromhost
    spec:
      containers:
      - name: hellofromhost
        image: picadoh/hellofromhost:v1
        ports:
        - containerPort: 8080
